version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /hitter
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /mocker
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /mocker
    schedule:
      interval: weekly
